name: DB deployment

on:
    push:
        branches: [ main ]
    
jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Clone the repository to the server
              uses: actions/checkout@v4
